name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: cd apps/web && npm install

      - name: List available scripts
        run: cd apps/web && npm run

      - name: Build project
        run: cd apps/web && npm run build:static

      - name: List build output
        run: cd apps/web && ls -la build/

      - name: List client directory
        run: cd apps/web && ls -la build/client/ || echo "Client directory not found"

      - name: Fix index.html paths
        run: |
          if [ -f "apps/web/build/client/index.html" ]; then
            cd apps/web/build/client
            sed -i 's|/assets/|./assets/|g' index.html
          else
            echo "index.html not found in build/client directory"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./apps/web/build/client