name: Test Build

on:
  push:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd apps/web && npm install

      - name: Build
        run: cd apps/web && npm run build

      - name: List build directory
        run: cd apps/web && ls -la build/
        
      - name: List client directory
        run: cd apps/web && ls -la build/client/